sudo: false
env:
  matrix:
    - LUA_VERSION=luajit-2.0
    - LUA_VERSION=luajit-2.1
    - LUA_VERSION=lua-5.1
    - LUA_VERSION=lua-5.2
    - LUA_VERSION=lua-5.3
cache:
  directories:
    - .venv
install:
  - source .envrc
  - script/bootstrap
script:
  - script/test
after_success:
  - script/travis-decrypt
  - script/deploy-docs
