sudo: false
env:
  global:
    - secure: Ai7wIggL88jnPTE89gviZWAgOa7Rvp5JkCPvr+BjAeC1rei5Awcf/9y6EvefG8VhxLDgAa/xwVBc7xrxCoqSjMRf50LKJDdhRRoT9evv+2mZTL9SQXbS0kYtqmWDNymbciwFhKZ/Qn0xuZhOsgsee0Erh8goVoizuB8MWzUw588kjb9PgeTzw5zkkU7xyqp9VjUG4JY/LgY59onoBRR2bPyOfXFF4oWuih89n4zaliLz+KO9/Ziyi/GeilQuW0AeYlGB+BN1US9jW+ooyF19j1oUurUCUDKfU0zZuDJsO3e2SyDcDN3fcnCI5S9qA+jrnK3RZmEveA6+9v4dSDjwjjFkRz/wjy6SdCP94gOfmffvcHvtwe7clnMl6ASVDhuWeRA+4AzcuXHYDcqXV4cmj7gwo4B4wtiO4N7ksxsg+wEsnDF/uN1DUFBjO5yAxZyhwFsPBDp4gu/ajbPRUnn5sV1r3nylNjZIGy4sZ23xArm9NJbyR5RXCxGOMU+MgtucnVazzeLoTRSZD9ANoIHk9ciBxtCs72FU61/S7iApwYOxWEhKCCtyZKFcRgQVmMKeyHQT8qRI87g0/EY6s+SeoC53XNBCc611mmNZqO5geUWTfQfOtjtZ2Jd+xbkw06JMswsfLc8OJ4i5C5H/lYV+NvdlCXBsfYGc2PnDWoMSJ6s=  # LUAROCKS_KEY
  matrix:
    - LUA_VERSION=luajit-2.0
    - LUA_VERSION=luajit-2.1
    - LUA_VERSION=lua-5.1
    - LUA_VERSION=lua-5.2
    - LUA_VERSION=lua-5.3
cache:
  directories:
    - .venv
install:
  - source .envrc
  - script/bootstrap
script:
  - script/test
after_success:
  - script/travis-decrypt
  - script/deploy-docs
deploy:
  provider: script
  script: script/deploy-rocks
  skip_cleanup: true
  all_branches: true
  on:
    condition: |
      ( "$TRAVIS_BRANCH" = master || "$TRAVIS_TAG" = v* ) && "$LUA_VERSION" = lua-5.3
