#!/bin/sh
# vim: set ts=4:
#
# Runs tests and linters.
#
set -eu

cd "$(dirname "$0")/.."
. script/bootstrap


einfo 'Running linters'

luacheck $PKG_NAME/*

for rockspec in *.rockspec; do
	luarocks lint "$rockspec" || exit 1
done
