#!/bin/sh
# vim: set ts=4:
set -eu

. "$(dirname "$0")"/utils.sh

if [ -z "${encrypted_be665121ac17_key:-}" ]; then
	ewarn 'Decryption key is not available'
	exit 0
fi

einfo 'Decrypting .deploykey'
openssl aes-256-cbc \
	-K "$encrypted_be665121ac17_key" \
	-iv "$encrypted_be665121ac17_iv" \
	-in .deploykey.enc -out .deploykey -d
chmod 600 .deploykey
